DATASET: 'scannet'
BATCH_SIZE: 1
SAVE_SCENE_MESH: True
LOGDIR: './log/checkpoints/attentional'
SAVE_FREQ: 1
MODE: 'test'

TRAIN:
  PATH: '/mnt/raid/scanpb/ScanNet_Source/public/v2'
  EPOCHS: 50
  N_VIEWS: 9
  LR: 1e-3
  N_WORKERS: 8
  LREPOCHS: '12,24,48:2'

TEST:
  PATH: '/mnt/raid/scanpb/ScanNet_Source/public/v2'
  N_VIEWS: 9
  N_WORKERS: 4

MODEL:
  FP16_ON: False # FP16 or FP32
  AGGREGATION_ON: True # if false, using summation
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True

  LW: [1.0, 0.8, 0.64]

  THRESHOLDS: [0, 0, 0]
  POS_WEIGHT: 1.5

  AGGREGATION:
    MODE: 'attentional' # either transformer or attentional
    TRANSFORMER:
      N_VIEWS: 9
      DEPTH: 1
      HEADS: 2
      DIM_HEAD: 32
      MLP_DIM: 32
      DROPOUT: 0.0
      EMBED_DROPOUT: 0.0
